language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
jdk:
  - oraclejdk7

sudo: required

env:
  global:
    MALLOC_ARENA_MAX=2

addons:
  apt:
    packages:
      - python2.7
      - libmagic1

before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install -r ./scripts/requirements.txt --user


script: ./gradlew build --no-daemon

after_success: ./scripts/travis_upload_release_to_github.py
